# Generated by Django 5.2.7 on 2025-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.JSONField(default=list)),
                ('original_text', models.TextField()),
            ],
        ),
    ]
