# Generated by Django 5.2.7 on 2025-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_job_created_at_job_deadline_job_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
