# Generated by Django 5.2.7 on 2025-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0004_job_posted_by_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.JSONField(default=list),
        ),
    ]
