# Generated by Django 5.2.7 on 2025-10-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0005_job_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
