# Generated by Django 5.2.7 on 2025-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_alter_job_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('MUTUAL', 'Mutual')], default='PUBLIC', help_text='Who can view this job: Public, Private, or Mutual', max_length=10),
        ),
    ]
